[package]
name = "program_guest"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { version = "1.1.2", default-features = false, features = ["std"] }

alloy-primitives = { version = "0.7.7" }
alloy-sol-types = { version = "0.7.7" }